# Generated by Django 6.0.5 on 2026-05-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fashion',
            name='created_at',
        ),
        migrations.AddField(
            model_name='fashion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fashion_items/'),
        ),
        migrations.AddField(
            model_name='fashion',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
